baseURL = 'https://doverpottery.studio'
languageCode = 'en-us'
title = "DOVER POTTERY STUDIO"

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[author]
facebook = "https://www.facebook.com/doverpottery.studio"
instagram = "https://www.instagram.com/doverpottery.studio/"

[Params]
subtitle = "a learning artspace in downtown Dover, NH"
mainSections = ["posts"]
description = "Join our pottery classes in Dover and learn the art of pottery. Sign up today at Dover Pottery Studio."
logo = "img/dps-logo-v2-gold.png"
hideAuthor = true
tags = false

#[[menus.main]]
#name = 'Home'
#pageRef = '/'
#weight = 10

[[menus.main]]
name = 'Classes'
pageRef = '/classes'
weight = 20

[[menus.main]]
name = 'Pop-Up Pots'
pageRef = '/pop-up-pots'
weight = 25

[[menus.main]]
name = 'News'
pageRef = '/posts'
weight = 30

[[menus.main]]
name = 'Memberships'
pageRef = '/memberships'
weight = 40

[[menus.main]]
name = 'Supplies'
url = 'https://doverpotterystudio.kilnfire.com/supplies'
weight = 50

[[menus.main]]
name = 'About'
pageRef = '/about'
weight = 60

[[menus.main]]
name = 'Policies'
pageRef = '/policies'
weight = 70

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false # default is true

[markup.goldmark.parser.attribute]
title = true # default is true; applies to h1-h6 elements
block = true # default is false; applies to other block-level elements
